In [119]:
import gym
import numpy as np
import random

In [120]:
env = gym.make('FrozenLake-v1')

In [121]:
Q1 = {}
Q2 = {}
Q  = {}
for s in range(env.observation_space.n):
    for a in range(env.action_space.n):
        Q1[(s,a)] = 0.0
        Q2[(s,a)] = 0.0
        Q[(s,a)]  = 0.0

In [122]:
def epsilon_greedy(state, epsilon):
    if random.uniform(0,1) < epsilon:
        return env.action_space.sample()
    else:
        return max(list(range(env.action_space.n)), key = lambda x:
            Q1[(state,x)]+Q2[(state,x)])



In [123]:
alpha = 0.85
gamma = 0.90
epsilon = 0.8
num_episodes = 100000
num_timesteps = 5000

for i in range(num_episodes):
    s, info = env.reset()
    for t in range(num_timesteps):
        a = epsilon_greedy(s,epsilon)
        s_, r, done, _, _ = env.step(a)
        a_1 = np.argmax([Q1[s_, a] for a in range(env.action_space.n)])
        a_2 = np.argmax([Q2[s_, a] for a in range(env.action_space.n)])
        if random.random() < .5:
            Q1[(s,a)] += alpha * (r + gamma * Q2[(s_,a_1)]-Q1[(s,a)])
        else:
            Q2[(s,a)] += alpha * (r + gamma * Q1[(s_,a_2)]-Q2[(s,a)])
        s = s_
        if done:
            break
for key, value in Q.items():
    Q[key] = (Q1[key]+Q2[key])/2
    print(key)
    print(Q[key])

(0, 0)
0.0014959485746783008
(0, 1)
0.0010324767732470545
(0, 2)
6.246349648090779e-05
(0, 3)
0.0005064787069044716
(1, 0)
0.0003620107451739226
(1, 1)
0.004457837045191959
(1, 2)
0.007562944070931079
(1, 3)
0.0032581461272504085
(2, 0)
0.009117987261335565
(2, 1)
0.003376327693278127
(2, 2)
0.004056483996831318
(2, 3)
0.004057350078076698
(3, 0)
0.0031053860269025795
(3, 1)
8.494465742007302e-05
(3, 2)
1.6809191766899518e-05
(3, 3)
0.00012171310047555391
(4, 0)
0.0010176200847109656
(4, 1)
0.001260028793964028
(4, 2)
0.0013689813728104934
(4, 3)
0.0013348535630060246
(5, 0)
0.0
(5, 1)
0.0
(5, 2)
0.0
(5, 3)
0.0
(6, 0)
0.0798201315685454
(6, 1)
0.00464495001034858
(6, 2)
0.0409787373998006
(6, 3)
7.292465142413592e-06
(7, 0)
0.0
(7, 1)
0.0
(7, 2)
0.0
(7, 3)
0.0
(8, 0)
0.00010885036393488114
(8, 1)
0.02542671160186652
(8, 2)
0.03535745356071258
(8, 3)
0.0015302912605216282
(9, 0)
0.28173842304501096
(9, 1)
0.0006117337463077076
(9, 2)
0.2968810495083689
(9, 3)
0.03928883933775629
(10, 0)

In [124]:
optimal_policy = np.zeros(16)
for i in range(16):
    best_value_i = 0
    for j in range(4):
        if best_value_i < Q[(i, j)]:
            best_value_i = Q[(i, j)]
            optimal_policy[i] = j
print(optimal_policy)

optimal_policy = np.zeros(16)
for i in range(16):
    best_value_i = 0
    for j in range(4):
        if best_value_i < Q1[(i, j)]:
            best_value_i = Q1[(i, j)]
            optimal_policy[i] = j
print(optimal_policy)

optimal_policy = np.zeros(16)
for i in range(16):
    best_value_i = 0
    for j in range(4):
        if best_value_i < Q2[(i, j)]:
            best_value_i = Q2[(i, j)]
            optimal_policy[i] = j
print(optimal_policy)

[0. 2. 0. 0. 2. 0. 0. 0. 2. 2. 2. 0. 0. 3. 2. 0.]
[0. 2. 0. 0. 0. 0. 0. 0. 2. 0. 1. 0. 0. 3. 2. 0.]
[1. 1. 0. 3. 1. 0. 2. 0. 1. 2. 2. 0. 0. 3. 1. 0.]
